// <auto-generated />
using System;
using Governança_de_TI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Governança_de_TI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ContaBancariaModel", b =>
                {
                    b.Property<Guid>("IdConta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Agencia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Banco")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdContaBancaria")
                        .HasColumnType("int");

                    b.Property<string>("NomeConta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroConta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("SaldoAtual")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("SaldoInicial")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("StatusConta")
                        .HasColumnType("int");

                    b.Property<int>("TipoConta")
                        .HasColumnType("int");

                    b.HasKey("IdConta");

                    b.ToTable("ContasBancarias");
                });

            modelBuilder.Entity("Governança_de_TI.Models.Auditoria.AuditLogModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Acao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Detalhes")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("Governança_de_TI.Models.Auditoria.LogModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Detalhes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mensagem")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Origem")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Logs");
                });

            modelBuilder.Entity("Governança_de_TI.Models.Financeiro.LancamentoFinanceiroModel", b =>
                {
                    b.Property<Guid>("IdLancamento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Condicao")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataEmissao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataFluxo")
                        .HasColumnType("datetime2");

                    b.Property<string>("Documento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormaPagamento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("IdConta")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("IdLancamentoFinanceiro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdLancamentoFinanceiro"));

                    b.Property<Guid>("IdPessoa")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdSubcategoria")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdTipo")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("IntervaloDias")
                        .HasColumnType("int");

                    b.Property<int>("NumeroParcelas")
                        .HasColumnType("int");

                    b.Property<string>("Observacao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SequenciaDocumento")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TipoLancamento")
                        .HasColumnType("int");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("ValorOriginal")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("IdLancamento");

                    b.HasIndex("IdConta");

                    b.HasIndex("IdPessoa");

                    b.HasIndex("IdSubcategoria");

                    b.HasIndex("IdTipo");

                    b.ToTable("LancamentoFinanceiro");
                });

            modelBuilder.Entity("Governança_de_TI.Models.Financeiro.SaldoDiarioModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("IdConta")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("SaldoFinal")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("IdConta");

                    b.ToTable("SaldoDiario");
                });

            modelBuilder.Entity("Governança_de_TI.Models.Financeiro.TpLancamento.SubCategoriaModel", b =>
                {
                    b.Property<Guid>("IdSubcategoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("IdSubcategoriaInt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSubcategoriaInt"));

                    b.Property<Guid>("IdTipo")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdSubcategoria");

                    b.HasIndex("IdTipo");

                    b.ToTable("SubCategoria");
                });

            modelBuilder.Entity("Governança_de_TI.Models.Financeiro.TpLancamento.TipoLancamentoModel", b =>
                {
                    b.Property<Guid>("IdTipo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("IdTipoLancamento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTipoLancamento"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("IdTipo");

                    b.ToTable("TipoLancamento");
                });

            modelBuilder.Entity("Governança_de_TI.Models.Gamificacao.GamificacaoModel", b =>
                {
                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<string>("Nivel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Pontos")
                        .HasColumnType("int");

                    b.HasKey("UsuarioId");

                    b.ToTable("Gamificacoes");
                });

            modelBuilder.Entity("Governança_de_TI.Models.Gamificacao.PremioModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("IconeBootstrap")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("PontosNecessarios")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Premios");
                });

            modelBuilder.Entity("Governança_de_TI.Models.Gamificacao.UsuarioPremioModel", b =>
                {
                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<int>("PremioId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataConquista")
                        .HasColumnType("datetime2");

                    b.HasKey("UsuarioId", "PremioId");

                    b.HasIndex("PremioId");

                    b.ToTable("UsuarioPremios");
                });

            modelBuilder.Entity("Governança_de_TI.Models.TecgreenModels.ConsumoEnergiaModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataReferencia")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("ValorKwh")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("ConsumosEnergia");
                });

            modelBuilder.Entity("Governança_de_TI.Models.TecgreenModels.DashboardWidgetModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Campo1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Campo2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CampoDataFiltro")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CampoDimensao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CampoMetrica")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CamposLista")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DataFiltroFim")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataFiltroInicio")
                        .HasColumnType("datetime2");

                    b.Property<string>("Operacao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OperadorAvancado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ordem")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrdenarPor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Posicao")
                        .HasColumnType("int");

                    b.Property<string>("TabelaFonte")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoVisualizacao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DashboardWidgets");
                });

            modelBuilder.Entity("Governança_de_TI.Models.TecgreenModels.DepartamentoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Departamentos");
                });

            modelBuilder.Entity("Governança_de_TI.Models.TecgreenModels.DescarteModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CertificadoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CnpjEmpresa")
                        .HasMaxLength(18)
                        .HasColumnType("nvarchar(18)");

                    b.Property<DateTime>("DataColeta")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataDeCadastro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailEmpresa")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EmpresaColetora")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("EnviarEmail")
                        .HasColumnType("bit");

                    b.Property<int>("EquipamentoId")
                        .HasColumnType("int");

                    b.Property<string>("ImagemEquipamentoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observacao")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("PessoaResponsavelColeta")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("EquipamentoId");

                    b.ToTable("Descartes");
                });

            modelBuilder.Entity("Governança_de_TI.Models.TecgreenModels.EquipamentoModel", b =>
                {
                    b.Property<int>("CodigoItem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodigoItem"));

                    b.Property<string>("AnexoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DataCompra")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataDeCadastro")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataFimGarantia")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataUltimaManutencao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("DiasAlertaManutencao")
                        .HasColumnType("int");

                    b.Property<bool>("EnviarEmailAlerta")
                        .HasColumnType("bit");

                    b.Property<string>("FrequenciaManutencao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagemUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Modelo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Serie")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("TipoEquipamentoId")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<int?>("VidaUtilAnos")
                        .HasColumnType("int");

                    b.Property<DateTime?>("VidaUtilFim")
                        .HasColumnType("datetime2");

                    b.HasKey("CodigoItem");

                    b.HasIndex("TipoEquipamentoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Equipamentos");
                });

            modelBuilder.Entity("Governança_de_TI.Models.TecgreenModels.TipoEquipamentoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("TiposEquipamento");
                });

            modelBuilder.Entity("Governança_de_TI.Models.Usuario.UsuarioModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CaminhoFotoPerfil")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("DataDeCadastro")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataUltimoLogin")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DepartamentoId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Perfil")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("DepartamentoId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("LancamentoParcelaModel", b =>
                {
                    b.Property<Guid>("IdParcela")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DataPagamento")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataVencimento")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("IdContaBaixa")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdLancamento")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("IdParcelaFinanceiro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdParcelaFinanceiro"));

                    b.Property<int>("NumeroParcela")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("ValorPago")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("ValorParcela")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("IdParcela");

                    b.HasIndex("IdLancamento");

                    b.ToTable("LancamentosParcelas");
                });

            modelBuilder.Entity("PessoaModel", b =>
                {
                    b.Property<Guid>("IdPessoa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Documento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EnderecoBairro")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EnderecoCEP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EnderecoCidade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EnderecoComplemento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EnderecoLogradouro")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EnderecoNumero")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EnderecoUF")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdPessoaInt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPessoaInt"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observacao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefone1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefone2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TipoPessoa")
                        .HasColumnType("int");

                    b.HasKey("IdPessoa");

                    b.ToTable("Pessoas");
                });

            modelBuilder.Entity("Governança_de_TI.Models.Auditoria.AuditLogModel", b =>
                {
                    b.HasOne("Governança_de_TI.Models.Usuario.UsuarioModel", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Governança_de_TI.Models.Financeiro.LancamentoFinanceiroModel", b =>
                {
                    b.HasOne("ContaBancariaModel", "Conta")
                        .WithMany()
                        .HasForeignKey("IdConta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PessoaModel", "Pessoa")
                        .WithMany()
                        .HasForeignKey("IdPessoa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Governança_de_TI.Models.Financeiro.TpLancamento.SubCategoriaModel", "SubCategoria")
                        .WithMany()
                        .HasForeignKey("IdSubcategoria");

                    b.HasOne("Governança_de_TI.Models.Financeiro.TpLancamento.TipoLancamentoModel", "Tipo")
                        .WithMany()
                        .HasForeignKey("IdTipo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conta");

                    b.Navigation("Pessoa");

                    b.Navigation("SubCategoria");

                    b.Navigation("Tipo");
                });

            modelBuilder.Entity("Governança_de_TI.Models.Financeiro.SaldoDiarioModel", b =>
                {
                    b.HasOne("ContaBancariaModel", "ContaBancaria")
                        .WithMany()
                        .HasForeignKey("IdConta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContaBancaria");
                });

            modelBuilder.Entity("Governança_de_TI.Models.Financeiro.TpLancamento.SubCategoriaModel", b =>
                {
                    b.HasOne("Governança_de_TI.Models.Financeiro.TpLancamento.TipoLancamentoModel", "Categoria")
                        .WithMany("SubCategorias")
                        .HasForeignKey("IdTipo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("Governança_de_TI.Models.Gamificacao.GamificacaoModel", b =>
                {
                    b.HasOne("Governança_de_TI.Models.Usuario.UsuarioModel", "Usuario")
                        .WithOne("Gamificacao")
                        .HasForeignKey("Governança_de_TI.Models.Gamificacao.GamificacaoModel", "UsuarioId");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Governança_de_TI.Models.Gamificacao.UsuarioPremioModel", b =>
                {
                    b.HasOne("Governança_de_TI.Models.Gamificacao.PremioModel", "Premio")
                        .WithMany("UsuariosQueConquistaram")
                        .HasForeignKey("PremioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Governança_de_TI.Models.Usuario.UsuarioModel", "Usuario")
                        .WithMany("UsuarioPremios")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Premio");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Governança_de_TI.Models.TecgreenModels.DescarteModel", b =>
                {
                    b.HasOne("Governança_de_TI.Models.TecgreenModels.EquipamentoModel", "Equipamento")
                        .WithMany()
                        .HasForeignKey("EquipamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipamento");
                });

            modelBuilder.Entity("Governança_de_TI.Models.TecgreenModels.EquipamentoModel", b =>
                {
                    b.HasOne("Governança_de_TI.Models.TecgreenModels.TipoEquipamentoModel", "TipoEquipamento")
                        .WithMany()
                        .HasForeignKey("TipoEquipamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Governança_de_TI.Models.Usuario.UsuarioModel", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId");

                    b.Navigation("TipoEquipamento");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Governança_de_TI.Models.Usuario.UsuarioModel", b =>
                {
                    b.HasOne("Governança_de_TI.Models.TecgreenModels.DepartamentoModel", "Departamento")
                        .WithMany()
                        .HasForeignKey("DepartamentoId");

                    b.Navigation("Departamento");
                });

            modelBuilder.Entity("LancamentoParcelaModel", b =>
                {
                    b.HasOne("Governança_de_TI.Models.Financeiro.LancamentoFinanceiroModel", "LancamentoPai")
                        .WithMany("Parcelas")
                        .HasForeignKey("IdLancamento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LancamentoPai");
                });

            modelBuilder.Entity("Governança_de_TI.Models.Financeiro.LancamentoFinanceiroModel", b =>
                {
                    b.Navigation("Parcelas");
                });

            modelBuilder.Entity("Governança_de_TI.Models.Financeiro.TpLancamento.TipoLancamentoModel", b =>
                {
                    b.Navigation("SubCategorias");
                });

            modelBuilder.Entity("Governança_de_TI.Models.Gamificacao.PremioModel", b =>
                {
                    b.Navigation("UsuariosQueConquistaram");
                });

            modelBuilder.Entity("Governança_de_TI.Models.Usuario.UsuarioModel", b =>
                {
                    b.Navigation("Gamificacao");

                    b.Navigation("UsuarioPremios");
                });
#pragma warning restore 612, 618
        }
    }
}
